eclipse-uprotocol/up-transport-zenoh-rust

.gitignore
Cargo.toml
README.md
examples/publisher.rs
examples/rpc_client.rs
examples/rpc_server.rs
examples/subscriber.rs
rustfmt.toml
src/lib.rs
src/rpc.rs
src/utransport.rs
tests/integration_test.rs

The PR is the first implementation of up-client-zenoh-rust, which is ported from [uprotocol-rust-ulink-zenoh](https://github.com/ZettaScaleLabs/uprotocol-rust-ulink-zenoh)
The PR is not ready to be merged, because we still need some changes on [up-rust](https://github.com/eclipse-uprotocol/up-rust)
Related to #1

The initial implementation of up-client-zenoh-rust

---

Cargo.toml
examples/publisher.rs
examples/rpc_client.rs
examples/rpc_server.rs
examples/subscriber.rs
tests/integration_test.rs

As mentioned in #7, change the project name to up-client-zenoh-rust.

Change the name to up-client-zenoh

---

src/rpc.rs
src/utransport.rs

As title, the PR is to fix #14 issue

Fix TTL issue

---

Cargo.toml

Bump up-rust version

---

Cargo.toml
tests/publish.rs
tests/rpc.rs

Update up-rust and include https://github.com/eclipse-uprotocol/up-rust/pull/90

Don't use explicit UUID in the latest up-rust.

---

NOTICE.md
src/lib.rs
src/rpc.rs
src/utransport.rs
tests/blocking_callback.rs
tests/publish.rs
tests/register.rs
tests/rpc.rs
tests/test_lib.rs

@stevenhartley I updated the license header to be consistent with up-rust.

Update the license headers

---

src/lib.rs

@PLeVasseur As mentioned in #42, I created a constructor to accept Runtime. It seems like the only way to create Runtime is to use plugins, so I can't write tests for it. Let me know if you have any issues while using it.

Support init with Runtime

---

src/lib.rs
tests/test_lib.rs

Deal with https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/issues/43

Re-export all the Zenoh config.

---

Cargo.toml
tests/l2_rpc.rs

Use the latest up-rust before the release.

Bump up-rust to 0.1.5

---

README.md
examples/notification_receiver.rs
examples/notifier.rs
examples/rpc_client.rs
examples/rpc_server.rs

Deal with https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/issues/55

Add notification examples.

---

src/lib.rs
tests/publish.rs
tests/register.rs

Align with the update of up-spec https://github.com/eclipse-uprotocol/up-spec/pull/210

Update the resource ID combination based on up-spec

---

Cargo.lock
Cargo.toml
README.md
config/DEFAULT_CONFIG.json5
examples/common/mod.rs
examples/l2_rpc_client.rs
examples/rpc_client.rs

Able to provide configuration in the arguments to increase the flexibility.

Able to support passing config from arguments.

---

Cargo.lock
Cargo.toml
config/DEFAULT_CONFIG.json5
examples/common/mod.rs
rust-toolchain.toml
src/lib.rs
src/rpc.rs
src/utransport.rs

Deal with https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/issues/67

Bump zenoh to 1.0

---

.github/release.yml
.github/workflows/README.md
.github/workflows/check.yaml
.github/workflows/coverage.yaml
.github/workflows/nightly.yaml
.github/workflows/release.yaml
.github/workflows/verify-msrv.yaml
.github/workflows/x-build.yaml
Cargo.toml

Deal with https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/issues/66
"Stole" most of the flows from up-rust :laughing:

Update the CI workflow and add release workflow.

---

Cargo.lock
Cargo.toml

Bump the version to apply the recent changes

Bump to 0.2.0

---

Cargo.lock
Cargo.toml

@PLeVasseur Tag you as a notice

Bump version to 0.3.1

---

.github/workflows/check.yaml
.github/workflows/nightly.yaml
.github/workflows/verify-latest-deps.yaml
Cargo.lock
Cargo.toml
tests/l2_rpc.rs

addresses #96
Also adopted latest changes to CI jobs from up-rust

Update to up-rust 0.4

---

src/lib.rs

Solve https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/issues/100

Separate ue_id into ue_type and ue_instance.

---

Cargo.lock
Cargo.toml

bump up-rust

---

README.md
examples/common/mod.rs
examples/l2_rpc_client.rs
examples/notification_receiver.rs
examples/notifier.rs
examples/publisher.rs
examples/rpc_client.rs
examples/rpc_server.rs
examples/subscriber.rs
src/lib.rs
src/listener_registry.rs
src/uri_provider.rs
src/utransport.rs
tests/send_receive.rs
tests/test_lib.rs

Also factored out the listener registry into its own module to
improve testability and maintainability of the code.
Addresses #120

Limit number of listeners that can be registered

---

.github/workflows/check-dependencies.yaml
Cargo.lock
Cargo.toml
README.md

While Zenoh, up-rust, and up-spec have an update, the PR will bump their version.

Bump the version of Zenoh, up-spec, and up-rust.
