- Cargo.toml
- README.md
- examples/publisher.rs
- examples/rpc_client.rs
- examples/rpc_server.rs
- examples/subscriber.rs
- src/lib.rs
- src/rpc.rs
- src/utransport.rs
- tests/integration_test.rs
As titled, the PR is to fix the lint and build issue.
But we need to wait for the following PR to be merged.
https://github.com/eclipse-uprotocol/up-rust/pull/52
> Fix CI issues

- src/utransport.rs
- tests/integration_test.rs
As @PLeVasseur mentioned in #6, support Notification-style Publish.
> Support Notification-style Publish.

- src/utransport.rs
- tests/rpc.rs
In Zenoh, if the query doesn't be destroyed after replying, the queryable will reply with timeout.
While send_response, we should also remove the query from HashMap.
> Fix timeout issue in RPC

- Cargo.toml
- README.md
- src/lib.rs
- src/rpc.rs
- src/utransport.rs
- tests/blocking_callback.rs
- tests/publish.rs
- tests/register.rs
- tests/rpc.rs
- tests/test_lib.rs
- tests/ustreamer.rs
The PR is to support up-spec 1.5.8 
Close https://github.com/eclipse-uprotocol/up-client-zenoh-rust/issues/39
> Initial support 1.5.8

- Cargo.toml
Bumps to a version of up-rust with fix for UCode now being its own .proto
> Bump up-rust for UCode .proto fix

- src/utransport.rs
Added handling of the case where we're within a Tokio Runtime or not
* if we're within a Tokio Runtime use the current handle
* if not, use a dedicated Tokio Runtime we have (e.g. we're within an async-std executor)
To handle the current case / issue of trying to send a Request UMessage within a Zenoh Plugin on zenoh 0.11.0-rc3, which I _think_ still uses async-std. Therefore we need to ensure we use a dedicated Tokio Runtime in that case within up-transport-zenoh-rust.
With this change, we resolve [this issue](https://github.com/eclipse-uprotocol/up-streamer-rust/pull/17#:~:text=Issue%20with%20up%2Dtransport%2Dzenoh%2Drust%20assuming%20it%27s%20inside%20of%20a%20Tokio%20runtime%3F) pointed out on the up-linux-streamer-plugin PR:
> Issue with up-transport-zenoh-rust assuming it's inside …
> Added handling of the case where we're within a Tokio Runtime or not

- Cargo.toml
- src/lib.rs
- src/rpc.rs
- src/utransport.rs
- tests/test_lib.rs
Now up-rust and Zenoh are both using tracing instead of log. Migrate the log system to ensure consistency.
> Use tracing to replace log

- .github/workflows/pull-request.yaml
- README.md
- examples/common/mod.rs
- examples/publisher.rs
- examples/rpc_client.rs
- examples/rpc_server.rs
- examples/subscriber.rs
As discussed in https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/issues/46, we'll move the examples back
> Move examples back to up-transport-zenoh-rust.

- Cargo.toml
- examples/l2_rpc_client.rs
- examples/publisher.rs
- examples/rpc_client.rs
- examples/rpc_server.rs
- examples/subscriber.rs
- src/lib.rs
- src/rpc.rs
- src/uri_provider.rs
- src/utransport.rs
- tests/blocking_callback.rs
- tests/l2_rpc.rs
- tests/publish.rs
- tests/register.rs
- tests/rpc.rs
- tests/test_lib.rs
- tests/ustreamer.rs
The PR is to use the latest up-rust, including the following update:
1. remove `on_error` in UListener
2. Support ZenohRpcClient (New way for L2 API)
> Update to the latest up-rust (Support L2 API)

- Cargo.toml
- rust-toolchain.toml
- src/lib.rs
Fix the nightly msrv [CI error](https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/actions/runs/10104128685/job/27942593912).
Also specify the Rust toolchain version to avoid the error in the future.
> Fix the Rust toolchain version at 1.74.1.

- Cargo.toml
Now the CI kept failing. This is because the mismatch Rust tool version.
> Use the correct Rust version to fix MSRV issue.

- Cargo.lock
- Cargo.toml
Removed crates from Cargo.toml which are not used anywhere in the code.
Also moved deps which are required for examples only to dev-dependencies block.
> Remove obsolete dependencies

- Cargo.lock
- Cargo.toml
- examples/l2_rpc_client.rs
- src/lib.rs
- src/rpc.rs
- src/utransport.rs
- tests/l2_rpc.rs
- tests/rpc.rs
Also pinned pre-release version of Zenoh in order to prevent Cargo
from using a more recent  pre-release which might be incompatible
with the required one.
> Update to up-rust 0.2.0

- src/lib.rs
- src/uri_provider.rs
The functions for creating a new UPTransportZenoh have been changed
to accept TryInto<UUri> which allows clients to pass in either
strings or UUri structs.
> [#78] Support passing UUri into constructors

- .github/workflows/verify-msrv.yaml
- rust-toolchain.toml
Fix the CI failure
https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/actions/runs/11265771929/job/31328151458
If we use msrv 0.16.x, it needs at least Rust 1.78.0. I guess it will be good to support the minimum version we need.
Therefore, I decide to fix at 0.15.1.
> Pin to the older msrv version.

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/utransport.rs
Since Zenoh is ready to release 1.0, have a quick update.
However, an issue was found here. It still needs some investigation.
https://github.com/eclipse-zenoh/zenoh/issues/1552
> Bump Zenoh version to the official 1.0.0

- Cargo.lock
- Cargo.toml
Related to https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/issues/88
> Bump to 0.3.0

- Cargo.lock
- Cargo.toml
- examples/common/mod.rs
I just found `insert_json5` is a better way in examples code to avoid using unstable configuration API.
> Avoid using zenoh-unstable in the examples

- Cargo.lock
- Cargo.toml
Need to wait for https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/pull/93 to be merged.
> Bump to 0.4.0

- Cargo.lock
- Cargo.toml
As https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/issues/97, bump the Zenoh version.
> Bump Zenoh to 1.2.1

- Cargo.lock
- Cargo.toml
Since we have a breaking change on https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/pull/101, it would be better to release a new minor version.
> Bump to 0.5.0

- Cargo.lock
- Cargo.toml
- deny.toml
This fixes https://rustsec.org/advisories/RUSTSEC-2025-0009
> Upgrade to ring 0.17.13

- Cargo.lock
- Cargo.toml
Upgrade `up-transport-zenoh-rust` to include ring fix and apply `up-rust` update
> Bump to 0.6.0

- .github/workflows/release.yaml
Deal with https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/issues/109
> Disable the OFT CI in the release flow.

- .github/workflows/release.yaml
Forgot to remove the dependency in https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/pull/110
My bad. @sophokles73 Would you mind reviewing this again? Hopefully, I didn't miss anything this time...
> Remove the dependency of requirements-tracing.

- .github/workflows/check.yaml
- .github/workflows/release.yaml
Fix the failure that we can't get up-spec
https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/actions/runs/13914084354/job/38934123380
> Get the submodule (up-spec).

- deny.toml
Deal with the issue https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/issues/113
> Bypass the advisories from cargo deny about the crate paste.

- .env.oft-latest
- .github/workflows/latest-up-spec-compatibility.yaml
- .github/workflows/nightly.yaml
- .github/workflows/release.yaml
Adopted the way that up-spec reads in the OpenFastTrace configuration
params from an env file in the local workspace. This makes it easier
to adapt the file patterns and tags according to the evolvement of
up-spec. The former way of using GitHub repo variables for that
purpose was rather static and did not allow to use different sets of
patterns on different branches in the repo.
> Add workflow for checking latest spec compatibility

- .github/workflows/README.md
- .github/workflows/check.yaml
- .github/workflows/latest-up-spec-compatibility.yaml
- Cargo.lock
- Cargo.toml
- README.md
- src/lib.rs
Bumped crate version to 0.7.0 in order to reflect the changes.
Also fixed a few broken links in the documentation, removed unused url crate and moved serde_json to dev-dependencies.
> Update to up_rust 0.6

- .github/workflows/release.yaml
The release workflow has been adapted to allow a release to be
created and published even if not all requirements are covered (yet),
according to OpenFastTrace.
> Allow releasing with not all spec items covered

- Cargo.toml
- README.md
- examples/notification_receiver.rs
- examples/subscriber.rs
- src/lib.rs
- src/listener_registry.rs
Changed the transport to process incoming messages on the tokio runtime
that Zenoh's callback is running on. This provides for full flexibility
regarding the configuration of the tokio runtime and allows for more
efficient use of resources in scenarios where the transport is used
on a constrained environment.
Doc comments and examples have been updated to reflect this change and
to provide guidance on how to implement listeners that process messages
without blocking the incoming message callback.
> [#127] Process incoming messages on Zenoh's tokio runtime

- .github/workflows/check.yaml
- .github/workflows/latest-up-spec-compatibility.yaml
- Cargo.lock
- Cargo.toml
- README.md
- src/utransport.rs
- tests/authorization.rs
- tests/blocking_callback.rs
- tests/send_receive.rs
- tests/test_lib.rs
- tests/users.txt
Added integration tests for the authorization functionality of the
Zenoh transport. The tests cover scenarios for both authorized and
unauthorized clients, ensuring that the authorization mechanism
works as expected. The tests also verify that the access control
configuration is correctly applied, and that clients can only
publish and subscribe to topics they are authorized to access.
> Add integration tests for authorization

- .github/workflows/check-dependencies.yaml
As discussed in https://github.com/eclipse-uprotocol/ci-cd/issues/22, we don't do another check when a PR is merged into main.
This can help avoid too many requests to the license verification server.
> Don't check the dependencies when a PR is merged into main.
